services:
   mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - three-tier
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    volumes:
      - ./mysql-data:/var/lib/mysql

   flask-app:
      build: .
      container_name: flask-app
      networks:
        - three-tier
      environment:
        MYSQL_HOST: mysql
        MYSQL_PASSWORD: root
        MYSQL_USER: root
        MYSQL_DATABASE: devops

      depends_on:
        - mysql

   nginx:
       image: nginx:latest
       container_name: todo-nginx
       ports:
        - "80:80"
       networks:
        - "three-tier"
       volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
       depends_on:
        - flask-app

networks:
  three-tier:
